version: "3.8"
services:
  db:
    image: postgres:16-alpine
    container_name: postgres-for-debug
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: debug3
    ports:
      - "5432:5432"
    volumes:
      - debugLab3_pgdata:/var/lib/postgresql/data

volumes:
  debugLab3_pgdata:
