version: "3.8"
services:
  db:
    image: postgres:16-alpine
    container_name: postgres-lab3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab3db
    ports:
      - "5432:5432"
    volumes:
      - lab3_pgdata:/var/lib/postgresql/data

volumes:
  lab3_pgdata:
